sudo: false
notifications:
  email:
    on_success: change
on_failure: always

language: go

go:
  - 1.12.x
  - tip

install: true

# Anything in before_script that returns a nonzero exit code will flunk the
# build and immediately stop. It's sorta like having set -e enabled in bash.
# Make sure golangci-lint is vendored.
before_script:
  - go get github.com/stretchr/testify/assert
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enabled
