# File to the dpkg database
source: "/var/lib/dpkg/status"

# Include regex
include: ""

# Exclude regex
exclude: ""

# Bind ip (0.0.0.0 for all interfaces)
host: 0.0.0.0

# Port to bind to
port: 80

# Basic auth username and password
users:
  - name: admin
    password: admin